// Scale in the key of 512 
// Automatically generated by scaleGenerator.py 

#define  REST           0

#define  NOTE_C0      512
#define  NOTE_Cx0     542
#define  NOTE_D0      575
#define  NOTE_Dx0     609
#define  NOTE_E0      645
#define  NOTE_F0      683
#define  NOTE_Fx0     724
#define  NOTE_G0      767
#define  NOTE_Gx0     813
#define  NOTE_A0      861
#define  NOTE_Ax0     912
#define  NOTE_B0      967
#define  NOTE_C1     1024
#define  NOTE_Cx1    1085
#define  NOTE_D1     1149
#define  NOTE_Dx1    1218
#define  NOTE_E1     1290
#define  NOTE_F1     1367
#define  NOTE_Fx1    1448
#define  NOTE_G1     1534
#define  NOTE_Gx1    1625
#define  NOTE_A1     1722
#define  NOTE_Ax1    1825
#define  NOTE_B1     1933
#define  NOTE_C2     2048
#define  NOTE_Cx2    2170
#define  NOTE_D2     2299
#define  NOTE_Dx2    2435
#define  NOTE_E2     2580
#define  NOTE_F2     2734
#define  NOTE_Fx2    2896
#define  NOTE_G2     3069
#define  NOTE_Gx2    3251
#define  NOTE_A2     3444
#define  NOTE_Ax2    3649
#define  NOTE_B2     3866
#define  NOTE_C3     4096
#define  NOTE_Cx3    4340
#define  NOTE_D3     4598
#define  NOTE_Dx3    4871
#define  NOTE_E3     5161
#define  NOTE_F3     5468
#define  NOTE_Fx3    5793
#define  NOTE_G3     6137
#define  NOTE_Gx3    6502
#define  NOTE_A3     6889
#define  NOTE_Ax3    7298
#define  NOTE_B3     7732

#ifndef __SYNTH_SCALES_Y__
#define __SYNTH_SCALES_Y__


//uint16_t scale_C[] = {NOTE_C0, NOTE_D0, NOTE_E0, NOTE_F0, NOTE_G0, NOTE_A0, NOTE_B0, NOTE_C1, NOTE_D1, NOTE_E1, NOTE_F1, NOTE_G1, NOTE_A1, NOTE_B1, NOTE_C2, NOTE_D2, NOTE_E2, NOTE_F2, NOTE_G2, NOTE_A2, NOTE_B2, NOTE_C3, NOTE_D3, NOTE_E3, NOTE_F3, NOTE_G3, NOTE_A3, NOTE_B3};

//uint16_t scale_Chromatic[] = {NOTE_C0, NOTE_Cx0, NOTE_D0, NOTE_Dx0, NOTE_E0, NOTE_F0, NOTE_Fx0, NOTE_G0, NOTE_Gx0, NOTE_A0, NOTE_Ax0, NOTE_B0};

#endif
